@echo off
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
start crash.exe
exit

